openapi: 3.0.0
info:
  title: test api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test:
    get:
      summary: test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
      operationId: get-admin-aplicants
      parameters: []
      tags:
        - Applicants
    parameters: []
  '/test/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
