name: API reference generater

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  redoc-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install vue-cli
        run: sudo npm install -g @vue/cli

      - name: Deploy applicant
        run: |
          cd ./vue/vue-project
          npm install
          vue run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Copy HTML file to S3 bucket
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          cd ./dist
          ls -F | grep -v / | xargs -I {} aws s3 cp {} s3://$S3_BUCKET
          ls -F | grep / | xargs -I {} aws s3 cp {} s3://$S3_BUCKET --recursive
